[package]
name = "netfw"
version = "0.0.0"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
com = { git = "https://github.com/microsoft/com-rs", rev = "3693ab2" }
netfw-sys = { path = "./lib/netfw-sys" }
winapi = { version = "0.3.9", features = [ "oaidl", "objbase", "oleauto" ] }

[workspace]
members = [ "./lib/netfw-sys" ]
